"""Persistence contract implemented by AgentGate storage adapters."""

from __future__ import annotations

from collections.abc import Sequence
from datetime import datetime
from typing import Protocol

from agentgate.domain import (
    Dataset,
    DatasetVersion,
    EvaluationResult,
    EvaluationRun,
    Evaluator,
    EvaluatorDraft,
    EvaluatorSpec,
    RunStatus,
    SkillAnalysisReport,
    SkillAnalysisReview,
    TargetDescriptor,
    TargetRef,
    TargetType,
    Trace,
)


class AgentGateRepository(Protocol):
    def save_target_descriptor(self, descriptor: TargetDescriptor) -> None: ...
    def get_target_descriptor(
        self, content_sha256: str
    ) -> TargetDescriptor | None: ...
    def list_target_descriptors(
        self, ref: TargetRef | None = None
    ) -> list[TargetDescriptor]: ...

    def save_skill_analysis_report(self, report: SkillAnalysisReport) -> None: ...
    def get_skill_analysis_report(
        self, report_id: str
    ) -> SkillAnalysisReport | None: ...
    def list_skill_analysis_reports(
        self, target_descriptor_sha256: str, limit: int = 50
    ) -> list[SkillAnalysisReport]: ...
    def save_skill_analysis_review(
        self, report_id: str, review: SkillAnalysisReview
    ) -> None: ...
    def list_skill_analysis_reviews(
        self, report_id: str
    ) -> list[SkillAnalysisReview]: ...

    def save_evaluator(self, evaluator: Evaluator) -> None: ...
    def save_evaluator_with_draft(
        self, evaluator: Evaluator, draft: EvaluatorDraft
    ) -> None: ...
    def get_evaluator(self, evaluator_id: str) -> Evaluator | None: ...
    def list_evaluators(
        self, include_disabled: bool = False
    ) -> list[Evaluator]: ...
    def delete_unpublished_evaluator(self, evaluator_id: str) -> None: ...
    def save_evaluator_draft(self, draft: EvaluatorDraft) -> None: ...
    def get_evaluator_draft(
        self, evaluator_id: str
    ) -> EvaluatorDraft | None: ...
    def delete_evaluator_draft(
        self, evaluator_id: str, expected_draft_id: str
    ) -> None: ...
    def list_evaluator_versions(
        self, evaluator_id: str
    ) -> list[EvaluatorSpec]: ...
    def get_evaluator_version(
        self, evaluator_id: str, version: str
    ) -> EvaluatorSpec | None: ...
    def get_latest_evaluator_version(
        self, evaluator_id: str
    ) -> EvaluatorSpec | None: ...
    def publish_evaluator_draft(
        self, expected_draft_id: str, published: EvaluatorSpec
    ) -> None: ...

    def save_dataset(self, dataset: Dataset) -> None: ...
    def save_dataset_with_version(
        self, dataset: Dataset, version: DatasetVersion
    ) -> None: ...
    def get_dataset(self, dataset_id: str) -> Dataset | None: ...
    def list_datasets(self, include_archived: bool = False) -> list[Dataset]: ...
    def save_dataset_version(self, version: DatasetVersion) -> None: ...
    def get_published_dataset_version(
        self, dataset_id: str, version: int
    ) -> DatasetVersion | None: ...
    def get_latest_published_dataset_version(
        self, dataset_id: str
    ) -> DatasetVersion | None: ...
    def get_dataset_draft(self, dataset_id: str) -> DatasetVersion | None: ...
    def list_dataset_versions(
        self, dataset_id: str, include_draft: bool = True
    ) -> list[DatasetVersion]: ...
    def delete_dataset_draft(self, dataset_id: str, expected_draft_id: str) -> None: ...
    def replace_dataset_draft(
        self, expected_draft_id: str, published: DatasetVersion
    ) -> None: ...

    def save_run(self, run: EvaluationRun) -> None: ...
    def get_run(self, run_id: str) -> EvaluationRun | None: ...
    def list_runs(self, limit: int = 50) -> list[EvaluationRun]: ...
    def list_runs_by_dataset_version(
        self, dataset_id: str, version: int, limit: int = 50
    ) -> list[EvaluationRun]: ...
    def list_runs_by_case_content(
        self,
        dataset_id: str,
        version: int,
        case_id: str,
        content_sha256: str,
        limit: int = 50,
    ) -> list[EvaluationRun]: ...
    def list_runs_by_target_version(
        self,
        source_id: str,
        target_type: TargetType,
        target_id: str,
        version: str,
        limit: int = 50,
        *,
        content_sha256: str | None = None,
    ) -> list[EvaluationRun]: ...
    def list_runs_by_skill_version(
        self,
        source_id: str,
        skill_id: str,
        version: str,
        limit: int = 50,
        *,
        content_sha256: str | None = None,
    ) -> list[EvaluationRun]: ...
    def list_runs_by_evaluator_version(
        self, evaluator_id: str, version: str, limit: int = 50
    ) -> list[EvaluationRun]: ...
    def claim_pending_run(
        self, run_id: str, started_at: datetime
    ) -> EvaluationRun | None: ...
    def list_runs_by_status(
        self,
        status: RunStatus,
        limit: int | None = None,
        oldest_first: bool = False,
    ) -> list[EvaluationRun]: ...
    def count_runs_by_status(self) -> dict[RunStatus, int]: ...
    def save_trace(self, trace: Trace) -> None: ...
    def get_trace(self, run_id: str, case_id: str) -> Trace | None: ...
    def list_traces(self, run_id: str) -> list[Trace]: ...
    def save_results(self, results: Sequence[EvaluationResult]) -> None: ...
    def list_results(self, run_id: str) -> list[EvaluationResult]: ...
